// Country names and aliases to ISO 3166-1 alpha-2. Covers every UN member state (193), the two UN
// observer states, Kosovo, Taiwan and the territories job posts mention. Isomorphic.
//
// Sources (accessed 2026-09-17):
// - UN member states: https://www.un.org/en/about-us/member-states
// - ISO 3166-1 codes: https://www.iso.org/iso-3166-country-codes.html ("XK" for Kosovo is a
//   user-assigned code used by the European Commission and many registries, not an ISO code).
//
// Matching is case-sensitive on purpose: country names match when capitalized as proper nouns
// ("Poland") or in capitals ("POLAND"). That keeps "turkey sandwich" and "chad" out. Short codes
// match only in the exact forms listed ("US", "U.S.", "UK", "UAE").

/** ISO 3166-1 alpha-2, upper case ("MD"). Kosovo uses the user-assigned "XK". */
export type CountryCode = string;

/** [code, English short name, ...aliases]. The first entry is the display name. */
const COUNTRY_ROWS: ReadonlyArray<readonly [CountryCode, string, ...string[]]> = [
  ["AF", "Afghanistan"],
  ["AL", "Albania", "Shqipëria"],
  ["DZ", "Algeria"],
  ["AD", "Andorra"],
  ["AO", "Angola"],
  ["AG", "Antigua and Barbuda", "Antigua & Barbuda"],
  ["AR", "Argentina"],
  ["AM", "Armenia", "Republic of Armenia"],
  ["AU", "Australia"],
  ["AT", "Austria", "Österreich"],
  ["AZ", "Azerbaijan"],
  ["BS", "Bahamas", "The Bahamas"],
  ["BH", "Bahrain"],
  ["BD", "Bangladesh"],
  ["BB", "Barbados"],
  ["BY", "Belarus"],
  ["BE", "Belgium", "Belgique", "België"],
  ["BZ", "Belize"],
  ["BJ", "Benin"],
  ["BT", "Bhutan"],
  ["BO", "Bolivia", "Plurinational State of Bolivia"],
  ["BA", "Bosnia and Herzegovina", "Bosnia & Herzegovina", "Bosnia-Herzegovina", "Bosnia", "BiH"],
  ["BW", "Botswana"],
  ["BR", "Brazil", "Brasil"],
  ["BN", "Brunei", "Brunei Darussalam"],
  ["BG", "Bulgaria"],
  ["BF", "Burkina Faso"],
  ["BI", "Burundi"],
  ["CV", "Cabo Verde", "Cape Verde"],
  ["KH", "Cambodia"],
  ["CM", "Cameroon"],
  ["CA", "Canada"],
  ["CF", "Central African Republic"],
  ["TD", "Chad"],
  ["CL", "Chile"],
  ["CN", "China", "Mainland China", "China Mainland", "People's Republic of China", "PRC"],
  ["CO", "Colombia"],
  ["KM", "Comoros"],
  ["CG", "Republic of the Congo", "Congo-Brazzaville", "Congo Republic"],
  [
    "CD",
    "Democratic Republic of the Congo",
    "DR Congo",
    "DRC",
    "Congo-Kinshasa",
    "Democratic Republic of Congo",
  ],
  ["CR", "Costa Rica"],
  ["CI", "Côte d'Ivoire", "Cote d'Ivoire", "Côte d’Ivoire", "Ivory Coast"],
  ["HR", "Croatia", "Hrvatska"],
  ["CU", "Cuba"],
  ["CY", "Cyprus"],
  ["CZ", "Czechia", "Czech Republic", "Česko"],
  ["DK", "Denmark", "Danmark"],
  ["DJ", "Djibouti"],
  ["DM", "Dominica"],
  ["DO", "Dominican Republic"],
  ["EC", "Ecuador"],
  ["EG", "Egypt"],
  ["SV", "El Salvador"],
  ["GQ", "Equatorial Guinea"],
  ["ER", "Eritrea"],
  ["EE", "Estonia", "Eesti"],
  ["SZ", "Eswatini", "Swaziland"],
  ["ET", "Ethiopia"],
  ["FJ", "Fiji"],
  ["FI", "Finland", "Suomi"],
  ["FR", "France"],
  ["GA", "Gabon"],
  ["GM", "Gambia", "The Gambia"],
  // "Georgia" alone is also a US state; the matcher resolves it by context (see GEORGIA_NAME).
  ["GE", "Georgia", "Republic of Georgia", "Sakartvelo", "Грузія", "Грузії", "Грузия", "Грузии"],
  ["DE", "Germany", "Deutschland", "Deutschlands"],
  ["GH", "Ghana"],
  ["GR", "Greece", "Hellas"],
  ["GD", "Grenada"],
  ["GT", "Guatemala"],
  ["GN", "Guinea"],
  ["GW", "Guinea-Bissau"],
  ["GY", "Guyana"],
  ["HT", "Haiti"],
  ["HN", "Honduras"],
  ["HU", "Hungary", "Magyarország"],
  ["IS", "Iceland"],
  ["IN", "India"],
  ["ID", "Indonesia"],
  ["IR", "Iran", "Islamic Republic of Iran"],
  ["IQ", "Iraq"],
  ["IE", "Ireland", "Republic of Ireland", "Éire"],
  ["IL", "Israel"],
  ["IT", "Italy", "Italia"],
  ["JM", "Jamaica"],
  ["JP", "Japan"],
  ["JO", "Jordan"],
  ["KZ", "Kazakhstan"],
  ["KE", "Kenya"],
  ["KI", "Kiribati"],
  ["KP", "North Korea", "DPRK", "Democratic People's Republic of Korea"],
  ["KR", "South Korea", "Republic of Korea", "Korea, Republic of", "Korea"],
  ["KW", "Kuwait"],
  ["KG", "Kyrgyzstan", "Kyrgyz Republic"],
  ["LA", "Laos", "Lao PDR", "Lao People's Democratic Republic"],
  ["LV", "Latvia", "Latvija"],
  ["LB", "Lebanon"],
  ["LS", "Lesotho"],
  ["LR", "Liberia"],
  ["LY", "Libya"],
  ["LI", "Liechtenstein"],
  ["LT", "Lithuania", "Lietuva"],
  ["LU", "Luxembourg"],
  ["MG", "Madagascar"],
  ["MW", "Malawi"],
  ["MY", "Malaysia"],
  ["MV", "Maldives"],
  ["ML", "Mali"],
  ["MT", "Malta"],
  ["MH", "Marshall Islands"],
  ["MR", "Mauritania"],
  ["MU", "Mauritius"],
  ["MX", "Mexico", "México"],
  ["FM", "Micronesia", "Federated States of Micronesia"],
  [
    "MD",
    "Moldova",
    "Republic of Moldova",
    "Moldova, Republic of",
    "Moldova Republic",
    "Republica Moldova",
    "Молдова",
    "Молдови",
    "Молдовы",
    "Молдове",
    "Молдові",
  ],
  ["MC", "Monaco"],
  ["MN", "Mongolia"],
  ["ME", "Montenegro", "Crna Gora"],
  ["MA", "Morocco"],
  ["MZ", "Mozambique"],
  ["MM", "Myanmar", "Burma"],
  ["NA", "Namibia"],
  ["NR", "Nauru"],
  ["NP", "Nepal"],
  ["NL", "Netherlands", "The Netherlands", "Holland", "Nederland"],
  ["NZ", "New Zealand", "Aotearoa"],
  ["NI", "Nicaragua"],
  ["NE", "Niger"],
  ["NG", "Nigeria"],
  ["MK", "North Macedonia", "Macedonia", "Republic of North Macedonia"],
  ["NO", "Norway", "Norge"],
  ["OM", "Oman"],
  ["PK", "Pakistan"],
  ["PW", "Palau"],
  ["PA", "Panama", "Panamá"],
  ["PG", "Papua New Guinea"],
  ["PY", "Paraguay"],
  ["PE", "Peru", "Perú"],
  ["PH", "Philippines", "The Philippines"],
  ["PL", "Poland", "Polska", "Polsce", "Polski", "Polskę", "Польша", "Польщі", "Польши"],
  ["PT", "Portugal"],
  ["QA", "Qatar"],
  ["RO", "Romania", "România"],
  ["RU", "Russia", "Russian Federation"],
  ["RW", "Rwanda"],
  ["KN", "Saint Kitts and Nevis", "St Kitts and Nevis", "St. Kitts and Nevis"],
  ["LC", "Saint Lucia", "St Lucia", "St. Lucia"],
  [
    "VC",
    "Saint Vincent and the Grenadines",
    "St Vincent and the Grenadines",
    "St. Vincent and the Grenadines",
  ],
  ["WS", "Samoa"],
  ["SM", "San Marino"],
  ["ST", "Sao Tome and Principe", "São Tomé and Príncipe"],
  ["SA", "Saudi Arabia", "Kingdom of Saudi Arabia", "KSA"],
  ["SN", "Senegal"],
  ["RS", "Serbia", "Srbija", "Republic of Serbia"],
  ["SC", "Seychelles"],
  ["SL", "Sierra Leone"],
  ["SG", "Singapore"],
  ["SK", "Slovakia", "Slovak Republic"],
  ["SI", "Slovenia", "Slovenija"],
  ["SB", "Solomon Islands"],
  ["SO", "Somalia"],
  ["ZA", "South Africa"],
  ["SS", "South Sudan"],
  ["ES", "Spain", "España"],
  ["LK", "Sri Lanka"],
  ["SD", "Sudan"],
  ["SR", "Suriname"],
  ["SE", "Sweden", "Sverige"],
  ["CH", "Switzerland", "Schweiz", "Suisse", "Svizzera"],
  ["SY", "Syria", "Syrian Arab Republic"],
  ["TJ", "Tajikistan"],
  ["TZ", "Tanzania", "United Republic of Tanzania"],
  ["TH", "Thailand"],
  ["TL", "Timor-Leste", "East Timor"],
  ["TG", "Togo"],
  ["TO", "Tonga"],
  ["TT", "Trinidad and Tobago", "Trinidad & Tobago"],
  ["TN", "Tunisia"],
  ["TR", "Türkiye", "Turkiye", "Turkey"],
  ["TM", "Turkmenistan"],
  ["TV", "Tuvalu"],
  ["UG", "Uganda"],
  [
    "UA",
    "Ukraine",
    "Україна",
    "України",
    "Україні",
    "Україну",
    "Украина",
    "Украины",
    "Украине",
    "Украину",
  ],
  ["AE", "United Arab Emirates", "UAE", "U.A.E."],
  [
    "GB",
    "United Kingdom",
    "UK",
    "U.K.",
    "Great Britain",
    "Britain",
    "United Kingdom of Great Britain and Northern Ireland",
    "England",
    "Scotland",
    "Wales",
    "Northern Ireland",
    "United Kindom",
  ],
  [
    "US",
    "United States",
    "United States of America",
    "USA",
    "U.S.A.",
    "US",
    "U.S.",
    "U.S",
    "the States",
    "США",
    "Estados Unidos",
    "EE.UU.",
  ],
  ["UY", "Uruguay"],
  ["UZ", "Uzbekistan"],
  ["VU", "Vanuatu"],
  ["VE", "Venezuela", "Bolivarian Republic of Venezuela"],
  ["VN", "Vietnam", "Viet Nam"],
  ["YE", "Yemen"],
  ["ZM", "Zambia"],
  ["ZW", "Zimbabwe"],
  // UN observer states.
  ["VA", "Holy See", "Vatican City", "Vatican"],
  ["PS", "Palestine", "State of Palestine"],
  // Not UN members, but job posts name them as places people live.
  ["XK", "Kosovo"],
  ["TW", "Taiwan"],
  ["HK", "Hong Kong", "Hong Kong SAR"],
  ["MO", "Macao", "Macau"],
  ["PR", "Puerto Rico"],
  ["GL", "Greenland"],
  ["FO", "Faroe Islands"],
  ["GI", "Gibraltar"],
  ["IM", "Isle of Man"],
  ["JE", "Jersey"],
  ["GG", "Guernsey"],
  ["BM", "Bermuda"],
  ["KY", "Cayman Islands"],
  ["AW", "Aruba"],
  ["CW", "Curaçao", "Curacao"],
  ["RE", "Réunion", "Reunion"],
  ["GU", "Guam"],
  ["VI", "US Virgin Islands", "U.S. Virgin Islands"],
  ["VG", "British Virgin Islands"],
  ["NC", "New Caledonia"],
  ["PF", "French Polynesia"],
  ["GF", "French Guiana"],
  ["GP", "Guadeloupe"],
  ["MQ", "Martinique"],
  ["AX", "Åland Islands", "Aland Islands"],
];

export interface CountryInfo {
  code: CountryCode;
  name: string;
  aliases: readonly string[];
}

export const COUNTRIES: ReadonlyMap<CountryCode, CountryInfo> = new Map(
  COUNTRY_ROWS.map(([code, name, ...aliases]) => [code, { code, name, aliases }]),
);

/** Codes of the 193 UN member states plus observers, Kosovo and territories listed above. */
export const COUNTRY_CODES: readonly CountryCode[] = [...COUNTRIES.keys()];

/** Pemby's target countries today (PLAN): Moldova first, then Ukraine, Georgia, Armenia, Balkans. */
export const TARGET_COUNTRIES = [
  "MD",
  "UA",
  "GE",
  "AM",
  "RS",
  "BA",
  "ME",
  "MK",
  "AL",
  "XK",
] as const;

/** The name "Georgia" is a country (GE) and a US state; callers must disambiguate. */
export const GEORGIA_NAME = "Georgia";

export function isCountryCode(value: string): boolean {
  return COUNTRIES.has(value);
}

export function countryName(code: CountryCode): string | undefined {
  return COUNTRIES.get(code)?.name;
}

/** ISO alpha-3 codes seen as prefixes in ATS location strings ("USA-CA-San Mateo", "GBR-London"). */
export const ALPHA3_TO_ALPHA2: ReadonlyMap<string, CountryCode> = new Map([
  ["USA", "US"],
  ["CAN", "CA"],
  ["MEX", "MX"],
  ["BRA", "BR"],
  ["ARG", "AR"],
  ["COL", "CO"],
  ["CHL", "CL"],
  ["GBR", "GB"],
  ["IRL", "IE"],
  ["DEU", "DE"],
  ["FRA", "FR"],
  ["NLD", "NL"],
  ["BEL", "BE"],
  ["ESP", "ES"],
  ["PRT", "PT"],
  ["ITA", "IT"],
  ["CHE", "CH"],
  ["AUT", "AT"],
  ["POL", "PL"],
  ["CZE", "CZ"],
  ["ROU", "RO"],
  ["BGR", "BG"],
  ["HUN", "HU"],
  ["SWE", "SE"],
  ["DNK", "DK"],
  ["NOR", "NO"],
  ["FIN", "FI"],
  ["EST", "EE"],
  ["LVA", "LV"],
  ["LTU", "LT"],
  ["GRC", "GR"],
  ["TUR", "TR"],
  ["ISR", "IL"],
  ["ARE", "AE"],
  ["IND", "IN"],
  ["PAK", "PK"],
  ["SGP", "SG"],
  ["JPN", "JP"],
  ["KOR", "KR"],
  ["CHN", "CN"],
  ["HKG", "HK"],
  ["TWN", "TW"],
  ["AUS", "AU"],
  ["NZL", "NZ"],
  ["ZAF", "ZA"],
  ["NGA", "NG"],
  ["KEN", "KE"],
  ["EGY", "EG"],
  ["MDA", "MD"],
  ["UKR", "UA"],
  ["GEO", "GE"],
  ["ARM", "AM"],
  ["SRB", "RS"],
  ["BIH", "BA"],
  ["MNE", "ME"],
  ["MKD", "MK"],
  ["ALB", "AL"],
  ["XKX", "XK"],
  ["PHL", "PH"],
  ["VNM", "VN"],
  ["IDN", "ID"],
  ["MYS", "MY"],
  ["THA", "TH"],
]);
