// Sub-national places job posts use in location strings and residence rules: US states, Canadian
// provinces, a few Australian/Indian/UK regions, and tech-hub cities. They resolve to a country
// only; they never widen eligibility on their own. Isomorphic.

import type { CountryCode } from "./countries";

/** US states and DC. "Georgia" is left out: it is resolved by context in `match.ts`. */
export const US_STATES: ReadonlyArray<readonly [abbr: string, name: string]> = [
  ["AL", "Alabama"],
  ["AK", "Alaska"],
  ["AZ", "Arizona"],
  ["AR", "Arkansas"],
  ["CA", "California"],
  ["CO", "Colorado"],
  ["CT", "Connecticut"],
  ["DE", "Delaware"],
  ["DC", "District of Columbia"],
  ["FL", "Florida"],
  ["HI", "Hawaii"],
  ["ID", "Idaho"],
  ["IL", "Illinois"],
  ["IN", "Indiana"],
  ["IA", "Iowa"],
  ["KS", "Kansas"],
  ["KY", "Kentucky"],
  ["LA", "Louisiana"],
  ["ME", "Maine"],
  ["MD", "Maryland"],
  ["MA", "Massachusetts"],
  ["MI", "Michigan"],
  ["MN", "Minnesota"],
  ["MS", "Mississippi"],
  ["MO", "Missouri"],
  ["MT", "Montana"],
  ["NE", "Nebraska"],
  ["NV", "Nevada"],
  ["NH", "New Hampshire"],
  ["NJ", "New Jersey"],
  ["NM", "New Mexico"],
  ["NY", "New York"],
  ["NC", "North Carolina"],
  ["ND", "North Dakota"],
  ["OH", "Ohio"],
  ["OK", "Oklahoma"],
  ["OR", "Oregon"],
  ["PA", "Pennsylvania"],
  ["RI", "Rhode Island"],
  ["SC", "South Carolina"],
  ["SD", "South Dakota"],
  ["TN", "Tennessee"],
  ["TX", "Texas"],
  ["UT", "Utah"],
  ["VT", "Vermont"],
  ["VA", "Virginia"],
  ["WA", "Washington"],
  ["WV", "West Virginia"],
  ["WI", "Wisconsin"],
  ["WY", "Wyoming"],
];

/** The two-letter code for Georgia (US state), handled with the name. */
export const US_GEORGIA_ABBR = "GA";

export const CA_PROVINCES: ReadonlyArray<readonly [abbr: string, name: string]> = [
  ["AB", "Alberta"],
  ["BC", "British Columbia"],
  ["MB", "Manitoba"],
  ["NB", "New Brunswick"],
  ["NL", "Newfoundland and Labrador"],
  ["NS", "Nova Scotia"],
  ["ON", "Ontario"],
  ["PE", "Prince Edward Island"],
  ["QC", "Quebec"],
  ["SK", "Saskatchewan"],
  ["NT", "Northwest Territories"],
  ["NU", "Nunavut"],
  ["YT", "Yukon"],
];

/** Other sub-national names that are unambiguous in job posts. */
export const OTHER_SUBDIVISIONS: ReadonlyArray<readonly [name: string, country: CountryCode]> = [
  ["Québec", "CA"],
  ["New South Wales", "AU"],
  ["Queensland", "AU"],
  ["Western Australia", "AU"],
  ["South Australia", "AU"],
  ["Tasmania", "AU"],
  ["Australian Capital Territory", "AU"],
  ["Karnataka", "IN"],
  ["Karnātaka", "IN"],
  ["Telangana", "IN"],
  ["Maharashtra", "IN"],
  ["Tamil Nadu", "IN"],
  ["Delhi NCR", "IN"],
  ["Haryana", "IN"],
  ["Punjab, Pakistan", "PK"],
  ["Sindh", "PK"],
  ["Catalunya", "ES"],
  ["Catalonia", "ES"],
  ["Bavaria", "DE"],
  ["Bayern", "DE"],
  ["Baden-Württemberg", "DE"],
  ["Masovian Voivodeship", "PL"],
  ["Mazowieckie", "PL"],
  ["Greater London", "GB"],
  ["Transnistria", "MD"],
  ["Gagauzia", "MD"],
];

/**
 * Cities. Only names that point to one country in tech job posts. Left out on purpose: Cambridge,
 * San Jose, Santiago, Valencia, Victoria, Waterloo, Georgetown, Kingston (several countries).
 */
export const CITIES: ReadonlyArray<readonly [name: string, country: CountryCode]> = [
  // Target countries.
  ["Chisinau", "MD"],
  ["Chișinău", "MD"],
  ["Chişinău", "MD"],
  ["Kishinev", "MD"],
  ["Balti", "MD"],
  ["Bălți", "MD"],
  ["Kyiv", "UA"],
  ["Kiev", "UA"],
  ["Lviv", "UA"],
  ["Kharkiv", "UA"],
  ["Odesa", "UA"],
  ["Odessa", "UA"],
  ["Dnipro", "UA"],
  ["Tbilisi", "GE"],
  ["Batumi", "GE"],
  ["Kutaisi", "GE"],
  ["Yerevan", "AM"],
  ["Belgrade", "RS"],
  ["Beograd", "RS"],
  ["Novi Sad", "RS"],
  ["Niš", "RS"],
  ["Sarajevo", "BA"],
  ["Banja Luka", "BA"],
  ["Podgorica", "ME"],
  ["Skopje", "MK"],
  ["Tirana", "AL"],
  ["Tirane", "AL"],
  ["Pristina", "XK"],
  ["Prishtina", "XK"],
  // Europe.
  ["London", "GB"],
  ["Manchester", "GB"],
  ["Edinburgh", "GB"],
  ["Bristol", "GB"],
  ["Oxford", "GB"],
  ["Belfast", "GB"],
  ["Dublin", "IE"],
  ["Cork", "IE"],
  ["Berlin", "DE"],
  ["Munich", "DE"],
  ["München", "DE"],
  ["Hamburg", "DE"],
  ["Frankfurt", "DE"],
  ["Cologne", "DE"],
  ["Köln", "DE"],
  ["Stuttgart", "DE"],
  ["Leipzig", "DE"],
  ["Düsseldorf", "DE"],
  ["Paris", "FR"],
  ["Lyon", "FR"],
  ["Toulouse", "FR"],
  ["Bordeaux", "FR"],
  ["Nantes", "FR"],
  ["Amsterdam", "NL"],
  ["Rotterdam", "NL"],
  ["Utrecht", "NL"],
  ["Eindhoven", "NL"],
  ["Brussels", "BE"],
  ["Ghent", "BE"],
  ["Antwerp", "BE"],
  ["Madrid", "ES"],
  ["Barcelona", "ES"],
  ["Malaga", "ES"],
  ["Málaga", "ES"],
  ["Lisbon", "PT"],
  ["Lisboa", "PT"],
  ["Porto", "PT"],
  ["Milan", "IT"],
  ["Milano", "IT"],
  ["Rome", "IT"],
  ["Turin", "IT"],
  ["Zurich", "CH"],
  ["Zürich", "CH"],
  ["Geneva", "CH"],
  ["Lausanne", "CH"],
  ["Zug", "CH"],
  ["Vienna", "AT"],
  ["Wien", "AT"],
  ["Warsaw", "PL"],
  ["Warszawa", "PL"],
  ["Krakow", "PL"],
  ["Kraków", "PL"],
  ["Wroclaw", "PL"],
  ["Wrocław", "PL"],
  ["Gdansk", "PL"],
  ["Gdańsk", "PL"],
  ["Poznan", "PL"],
  ["Poznań", "PL"],
  ["Lodz", "PL"],
  ["Łódź", "PL"],
  ["Prague", "CZ"],
  ["Praha", "CZ"],
  ["Brno", "CZ"],
  ["Bratislava", "SK"],
  ["Budapest", "HU"],
  ["Bucharest", "RO"],
  ["București", "RO"],
  ["Cluj-Napoca", "RO"],
  ["Cluj", "RO"],
  ["Iasi", "RO"],
  ["Iași", "RO"],
  ["Timisoara", "RO"],
  ["Timișoara", "RO"],
  ["Brasov", "RO"],
  ["Sofia", "BG"],
  ["Plovdiv", "BG"],
  ["Zagreb", "HR"],
  ["Ljubljana", "SI"],
  ["Stockholm", "SE"],
  ["Gothenburg", "SE"],
  ["Malmö", "SE"],
  ["Copenhagen", "DK"],
  ["Aarhus", "DK"],
  ["Oslo", "NO"],
  ["Helsinki", "FI"],
  ["Tallinn", "EE"],
  ["Tartu", "EE"],
  ["Riga", "LV"],
  ["Vilnius", "LT"],
  ["Kaunas", "LT"],
  ["Istanbul", "TR"],
  ["Istambul", "TR"],
  ["Ankara", "TR"],
  ["Nicosia", "CY"],
  ["Limassol", "CY"],
  ["Luxembourg City", "LU"],
  ["Valletta", "MT"],
  ["Sliema", "MT"],
  ["Reykjavik", "IS"],
  ["Minsk", "BY"],
  ["Moscow", "RU"],
  ["Saint Petersburg", "RU"],
  ["Baku", "AZ"],
  ["Almaty", "KZ"],
  ["Astana", "KZ"],
  ["Tashkent", "UZ"],
  // Americas.
  ["New York City", "US"],
  ["NYC", "US"],
  ["Jersey City", "US"],
  ["San Francisco", "US"],
  ["San Francisco Bay Area", "US"],
  ["Bay Area", "US"],
  ["Silicon Valley", "US"],
  ["Los Angeles", "US"],
  ["Seattle", "US"],
  ["Austin", "US"],
  ["Boston", "US"],
  ["Chicago", "US"],
  ["Denver", "US"],
  ["Atlanta", "US"],
  ["Miami", "US"],
  ["Dallas", "US"],
  ["Houston", "US"],
  ["Phoenix", "US"],
  ["Philadelphia", "US"],
  ["Pittsburgh", "US"],
  ["Palo Alto", "US"],
  ["Mountain View", "US"],
  ["Menlo Park", "US"],
  ["Sunnyvale", "US"],
  ["Santa Clara", "US"],
  ["San Mateo", "US"],
  ["San Diego", "US"],
  ["Redmond", "US"],
  ["Bellevue", "US"],
  ["Salt Lake City", "US"],
  ["Washington, DC", "US"],
  ["Washington DC", "US"],
  ["Washington D.C.", "US"],
  ["Toronto", "CA"],
  ["Vancouver", "CA"],
  ["Montreal", "CA"],
  ["Montréal", "CA"],
  ["Ottawa", "CA"],
  ["Calgary", "CA"],
  ["Mexico City", "MX"],
  ["Ciudad de México", "MX"],
  ["CDMX", "MX"],
  ["Guadalajara", "MX"],
  ["Monterrey", "MX"],
  ["Querétaro", "MX"],
  ["São Paulo", "BR"],
  ["Sao Paulo", "BR"],
  ["Rio de Janeiro", "BR"],
  ["Florianópolis", "BR"],
  ["Belo Horizonte", "BR"],
  ["Buenos Aires", "AR"],
  ["Córdoba, Argentina", "AR"],
  ["Bogotá", "CO"],
  ["Bogota", "CO"],
  ["Medellín", "CO"],
  ["Medellin", "CO"],
  ["Lima", "PE"],
  ["Montevideo", "UY"],
  ["Quito", "EC"],
  // Asia, Africa, Oceania.
  ["Bengaluru", "IN"],
  ["Bangalore", "IN"],
  ["Hyderabad", "IN"],
  ["Pune", "IN"],
  ["Mumbai", "IN"],
  ["Chennai", "IN"],
  ["Noida", "IN"],
  ["Gurgaon", "IN"],
  ["Gurugram", "IN"],
  ["New Delhi", "IN"],
  ["Karachi", "PK"],
  ["Lahore", "PK"],
  ["Islamabad", "PK"],
  ["Dhaka", "BD"],
  ["Chittagong", "BD"],
  ["Colombo", "LK"],
  ["Kathmandu", "NP"],
  ["Tel Aviv", "IL"],
  ["Jerusalem", "IL"],
  ["Dubai", "AE"],
  ["Abu Dhabi", "AE"],
  ["Riyadh", "SA"],
  ["Doha", "QA"],
  ["Cairo", "EG"],
  ["Casablanca", "MA"],
  ["Tunis", "TN"],
  ["Lagos", "NG"],
  ["Abuja", "NG"],
  ["Nairobi", "KE"],
  ["Accra", "GH"],
  ["Kigali", "RW"],
  ["Cape Town", "ZA"],
  ["Johannesburg", "ZA"],
  ["Singapore City", "SG"],
  ["Kuala Lumpur", "MY"],
  ["Jakarta", "ID"],
  ["Manila", "PH"],
  ["Metro Manila", "PH"],
  ["Bangkok", "TH"],
  ["Ho Chi Minh City", "VN"],
  ["Hanoi", "VN"],
  ["Tokyo", "JP"],
  ["Osaka", "JP"],
  ["Seoul", "KR"],
  ["Taipei", "TW"],
  ["Shanghai", "CN"],
  ["Beijing", "CN"],
  ["Shenzhen", "CN"],
  ["Sydney", "AU"],
  ["Melbourne", "AU"],
  ["Brisbane", "AU"],
  ["Perth", "AU"],
  ["Canberra", "AU"],
  ["Auckland", "NZ"],
  ["Wellington", "NZ"],
];

/**
 * Phrases that contain a country or region name but are not that place. The matcher consumes them
 * first so the inner name does not match ("New Mexico" is not Mexico).
 */
export const NON_PLACE_PHRASES: readonly string[] = [
  "Bank of America",
  "African American",
  "African-American",
  "Asian American",
  "Asian-American",
  "Latin American Studies",
  "American Express",
  "Georgia Tech",
  "Georgia Institute of Technology",
  "Washington Post",
  "Central European Time",
  "Central European Summer Time",
  "Eastern European Time",
  "Eastern European Summer Time",
  "Western European Time",
  "Indian Ocean",
  "Europe's",
  "European Commission",
  "European Parliament",
  "European Accessibility Act",
  "EU AI Act",
  "EU Pay Transparency",
  "General Data Protection Regulation",
  "Phoenix/LiveView",
  "Phoenix LiveView",
  "Elixir/Phoenix",
  "Phoenix Framework",
  "Phoenix framework",
];
