// Reason and gap keys for the score. Templated, never generated by a model: PLAN D18 says matching
// is rules plus embeddings with templated reasons and no per-user LLM cost.
//
// PLAN D16 wording: every line describes the post or the user's own CV. None of them claims a
// company hires anyone.
//
// No line here may depend on grammatical number. `{skills}` and `{domains}` are comma-joined lists
// of one to three items, and ICU plurals are not an option: `renderScoreReason` below does naive
// `{param}` substitution for Telegram and email, so a template only next-intl could read would give
// those channels broken output. Phrase around number instead ("Matches what the post asks for:
// {skills}." rather than "{skills} match ..."), and keep every string here byte-identical to its
// twin in `apps/web/messages/en/brief.json`, which is the same key rendered through i18n.

export const SCORE_REASONS = {
  // reasons (top 3)
  "stack-match": "Matches what the post asks for: {skills}.",
  "stack-most": "You have {matched} of the {total} technologies the post names.",
  "domain-match": "You've worked in {domains}.",
  "timezone-overlap": "About {hours}h overlap with the hours the post asks for.",
  "similar-to-your-cv": "Close to the roles on your CV.",
  "company-fit": "The company matches what you asked for.",

  // gap (one)
  "stack-missing": "No {skills} on your CV.",
  "domain-new": "You haven't worked in {domains}.",
  "timezone-thin": "About {hours}h overlap; the post asks for {required}h.",
  "years-short": "The post asks {years} years; your CV shows {userYears}.",
  "seniority-step-up": "The post asks for {jobSeniority}; you're {userSeniority}.",
  "salary-not-listed": "The post doesn't list pay.",
  /** Shown instead of a low score when the job has no embedding yet. */
  "no-similarity-yet": "Not scored on similarity to your CV yet.",
} as const;

export type ScoreReasonKey = keyof typeof SCORE_REASONS;
export const SCORE_REASON_KEYS = Object.keys(SCORE_REASONS) as ScoreReasonKey[];

/** A key plus the values it fills. Never a rendered sentence. */
export interface ScoreReason {
  key: ScoreReasonKey;
  params: Record<string, string>;
}

/** Same cap as the eligibility engine, so reasons stack without reflowing. */
export const MAX_SCORE_REASON = 120;

/** English fallback rendering. The UI normally renders `key` + `params` through i18n instead. */
export function renderScoreReason(key: ScoreReasonKey, params: Record<string, string>): string {
  const text = SCORE_REASONS[key].replace(/\{(\w+)\}/g, (_, name: string) => params[name] ?? "");
  return text.length <= MAX_SCORE_REASON
    ? text
    : `${text.slice(0, MAX_SCORE_REASON - 3).trimEnd()}...`;
}
