// `@pemby/ai`: server-only. OpenRouter key routing, task routing (private `routing.json` over
// DEFAULT_ROUTING), structured task calls, the cost ledger contract, the daily cap and its owner
// alert, and prompt loading (prompts come from the private config, never from this repo).
export {
  AiConfigError,
  KEY_CLASSES,
  ZDR_PROVIDER_ROUTING,
  getOpenRouter,
  requiresZdr,
  withEnforcedZdr,
  type EnvLike,
  type KeyClass,
  type OpenRouterOptions,
} from "./keys";
export {
  AI_TASKS,
  DEFAULT_ROUTING,
  EMBEDDING_DIMENSIONS,
  EMBEDDING_MODEL,
  PersonalDataRoutingError,
  applyRoutingConfig,
  assertRouteAllowed,
  embeddingModelForTask,
  languageModelForTask,
  loadRoutingTable,
  resolveRoute,
  validateRoutingTable,
  type AiTask,
  type ModelKind,
  type ResolvedRoute,
  type RouteOptions,
  type RoutingConfig,
  type RoutingTable,
  type TaskParams,
  type TaskEmbeddingModel,
  type TaskLanguageModel,
  type TaskModelOptions,
  type TaskRoute,
} from "./routing";
export {
  DAILY_CAP_USD,
  DailyCapReachedError,
  countsTowardDailyCap,
  createDailyCapGuard,
  evaluateDailyCap,
  nextUtcMidnight,
  readDailyCapUsd,
  utcDay,
  type AiUsageEntry,
  type CostLedger,
  type DailyCapGuard,
  type DailyCapGuardOptions,
  type DailyCapStatus,
} from "./cost";
export {
  AiCallError,
  AiOutputInvalidError,
  AiPromptMissingError,
  runStreamingStructuredTask,
  runStructuredTask,
  type RouteOverride,
  type StreamingPartialMeta,
  type StreamingStructuredTaskOptions,
  type StreamingStructuredTaskResult,
  type StructuredTaskContext,
  type StructuredTaskOptions,
  type StructuredTaskResult,
} from "./structured";
export {
  estimateAttemptCost,
  estimateCostUsd,
  lookupGenerationUsage,
  type CostEstimate,
  type GenerationUsage,
} from "./usage";
export {
  alertOwnerCapReached,
  type CapAlertChannel,
  type CapAlertClaim,
  type CapAlertClaimInput,
  type CapAlertMarkDelivered,
  type CapAlertOptions,
  type CapAlertResult,
} from "./alert";
export { loadPrompt, type PromptTemplate } from "@pemby/core/private-config";
